apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sip-server
  namespace: alwaysbespoke
  labels:
    app: sip-server
spec:
  selector:
    matchLabels:
      app: sip-server
  replicas: 1 
  template:
    metadata:
      labels:
        app: sip-server
    spec:
      containers:
      - name: sip-server
        image: sip-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        - containerPort: 6000