apiVersion: v1 
kind: Service
metadata:
  name: sip-server
  namespace: alwaysbespoke
spec:
  type: ClusterIP
  selector:
    app: sip-server
  ports:
  - name: udp
    port: 5000
    targetPort: 5000
  - name: tcp
    port: 6000
    targetPort: 6000