apiVersion: apps/v1 
kind: Deployment
metadata:
  name: sbc-service
  namespace: alwaysbespoke
  labels:
    app: sbc-service
spec:
  selector:
    matchLabels:
      app: sbc-service
  replicas: 1 
  template:
    metadata:
      labels:
        app: sbc-service
    spec:
      containers:
      - name: sbc-service
        image: sbc-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000