apiVersion: v1 
kind: Service
metadata:
  name: sbc-service
  namespace: alwaysbespoke
spec:
  type: ClusterIP
  selector:
    app: sbc-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000